//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string AccessoryId { get; set; }
        public int OrderId { get; set; }
        public int Quantity { get; set; }
        public string AccessoryName { get; set; }
        public string AccessoryCalculationUnit { get; set; }
        public Nullable<double> AccessoryPrice { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Order Order { get; set; }
    }
}
