//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiem
    {
        public int SinhVienID { get; set; }
        public int MonHocID { get; set; }
        public Nullable<double> TK { get; set; }
        public Nullable<double> GK { get; set; }
        public Nullable<double> CK { get; set; }
    }
}
